spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blackcoffer_assignment_project
    username: root
    password: Sushmi@123
    
  jpa:
    hibernate:
      ddl-auto: create
    
  